version: '3'
services:
  db:
    image: postgres:14
    container_name: joplin_postgres
    restart: always
    environment:
      POSTGRES_DB: joplin
      POSTGRES_USER: joplin
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: joplin/server:latest
    container_name: joplin_server
    restart: always
    depends_on:
      - db
    ports:
      - "22300:22300"
    environment:
      APP_PORT: 22300
      DB_CLIENT: pg
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DATABASE: joplin
      POSTGRES_USER: joplin
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db

volumes:
  postgres_data:
